# Generated by Django 4.1.7 on 2023-03-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='size',
            new_name='name',
        ),
    ]
