# Generated by Django 4.1.7 on 2023-03-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_favourite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='drink',
            field=models.CharField(max_length=30),
        ),
    ]
