# Generated by Django 4.1.7 on 2023-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_drink_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='recipes',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
