# Generated by Django 4.1.7 on 2023-03-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0003_alter_drink_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=50)),
                ('partner_name', models.CharField(max_length=50)),
                ('customization', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
