# Generated by Django 4.1.7 on 2023-03-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_rename_partner_name_barista_name_and_more'),
        ('favourites', '0004_review_delete_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='partner_name',
        ),
        migrations.AddField(
            model_name='review',
            name='partner_name',
            field=models.ManyToManyField(blank=True, related_name='partner_name', to='partner.barista'),
        ),
    ]
