# Generated by Django 4.1.7 on 2023-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0007_remove_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='drink_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
