# Generated by Django 4.1.7 on 2023-03-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0008_review_drink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='drink_image',
            field=models.ImageField(default='https://miro.medium.com/v2/resize:fit:720/format:webp/1*EN0fyh1x46dxsc-w20lRfw.jpeg', upload_to='images'),
        ),
    ]
