# Generated by Django 4.1.7 on 2023-03-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0009_alter_review_drink_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='partner_name',
            new_name='barista_name',
        ),
    ]
