# Generated by Django 4.1.7 on 2023-03-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0010_rename_partner_name_review_barista_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='barista_name',
            new_name='partner_name',
        ),
    ]
