# Generated by Django 4.1.7 on 2023-03-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='years_of_service',
            new_name='partner_number',
        ),
    ]
