# Generated by Django 4.1.7 on 2023-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=25)),
                ('partner_number', models.IntegerField()),
                ('coffee_master', models.BooleanField(default=False)),
            ],
        ),
    ]
