# Generated by Django 4.1.7 on 2023-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='fact',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
