# Generated by Django 4.1.7 on 2023-03-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_barista_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barista',
            name='coffee_master',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='coffee_master',
            field=models.DateField(),
        ),
    ]
