# Generated by Django 4.1.7 on 2023-03-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_alter_barista_coffee_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barista',
            name='coffee_master',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='coffee_master',
        ),
    ]
