# Generated by Django 4.1.7 on 2023-03-18 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_remove_barista_coffee_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barista',
            name='partner_number',
            field=models.IntegerField(verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='manager',
            name='partner_number',
            field=models.IntegerField(verbose_name=datetime.datetime),
        ),
    ]
