# Generated by Django 4.1.7 on 2023-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_barista_partner_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barista',
            name='coffee_master',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='coffee_master',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='barista',
            name='partner_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='partner_number',
            field=models.IntegerField(),
        ),
    ]
