# Generated by Django 4.1.7 on 2023-03-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_barista_coffee_master_manager_coffee_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barista',
            name='potq',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='potq',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='barista',
            name='coffee_master',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='coffee_master',
            field=models.BooleanField(default=True),
        ),
    ]
