# Generated by Django 4.1.7 on 2023-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_barista_potq_manager_potq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barista',
            name='potq',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='potq',
            field=models.BooleanField(default=True),
        ),
    ]
