# Generated by Django 4.1.7 on 2023-03-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_alter_barista_potq_alter_manager_potq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barista',
            name='coffee_master',
        ),
        migrations.RemoveField(
            model_name='barista',
            name='potq',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='coffee_master',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='potq',
        ),
    ]
