# Generated by Django 4.1.7 on 2023-03-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_remove_barista_coffee_master_remove_barista_potq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barista',
            old_name='name',
            new_name='partner_name',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='name',
            new_name='partner_name',
        ),
    ]
