# Generated by Django 4.1.7 on 2023-03-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_rename_name_barista_partner_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barista',
            old_name='partner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='partner_name',
            new_name='name',
        ),
    ]
