# Generated by Django 4.1.7 on 2023-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_rename_partner_name_barista_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barista',
            name='barista_image',
            field=models.ImageField(default='https://miro.medium.com/v2/resize:fit:720/format:webp/1*EN0fyh1x46dxsc-w20lRfw.jpeg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_image',
            field=models.ImageField(default='https://miro.medium.com/v2/resize:fit:720/format:webp/1*EN0fyh1x46dxsc-w20lRfw.jpeg', upload_to='images'),
        ),
    ]
