# Generated by Django 4.1.7 on 2023-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_barista_barista_image_manager_manager_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='barista',
            name='potq',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='potq',
            field=models.BooleanField(null=True),
        ),
    ]
