# Generated by Django 4.1.7 on 2023-03-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_barista_potq_manager_potq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barista',
            name='potq',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='potq',
            field=models.BooleanField(default=False),
        ),
    ]
