# Generated by Django 4.1.7 on 2023-03-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_alter_barista_potq_alter_manager_potq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barista',
            old_name='name',
            new_name='barista_name',
        ),
    ]
